### ISSUE TITLE
Your website was down!

### ISSUE THREAD

**Issue by NabiKAZ** [articlefr/CaptchaSolutions#5]
Your website was down! (https://www.captchasolutions.com/) , please check it.
2017-08-29
https://www.host-tracker.com/InstantCheck/3/87d691a2-3a8c-e711-892b-0003ff7328cc

**Comment by articlefr** [comment]
Website is fully functional now...

**Comment by NabiKAZ** [comment]
This was about 3 months ago.
I'm back to the site now.
Your site is very slow now. So opening the pages takes several minutes.
Your service is good, but why is your servers so weak that it's even difficult to open pages.
I read this problem in other forums about your site.
